on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  npm-audit-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: miyajan/npm-audit-pr@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
